spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: ''
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 30000
  session:
    store-type: redis
